# Generated by Django 4.1.1 on 2022-10-23 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iseme_sasa', '0002_offencecategory_police_victim_alter_user_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliceProfileImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='police_img_uploads')),
                ('police', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_image', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrackStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='policeimageupload',
            name='police',
        ),
        migrations.RemoveField(
            model_name='victimimageupload',
            name='victim',
        ),
        migrations.RemoveField(
            model_name='report',
            name='perpetrator_first_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='perpetrator_gender',
        ),
        migrations.RemoveField(
            model_name='report',
            name='perpetrator_last_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='perpetrator_name',
        ),
        migrations.RemoveField(
            model_name='victim',
            name='age',
        ),
        migrations.AddField(
            model_name='police',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='Perpetrator_Full_names',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='Perpetrator_Phone_Number',
            field=models.FloatField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='Relationship_with_perpetrator',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='any_other_message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='county',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='datetime',
            field=models.DateField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='offence_category',
            field=models.ForeignKey(help_text='Select the offence category.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='iseme_sasa.offencecategory'),
        ),
        migrations.AddField(
            model_name='report',
            name='where_committed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='dateofBirth',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='relation_with_perpetrator',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='offencecategory',
            name='name',
            field=models.CharField(help_text='Select a category (EG: Rape)', max_length=200),
        ),
        migrations.AlterField(
            model_name='victim',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='victim',
            name='social_status',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='PoliceImageUpload',
        ),
        migrations.DeleteModel(
            name='VictimImageUpload',
        ),
    ]
